/**:
  ros__parameters:
    robot_description_kinematics:
      ur_manipulator:
        kinematics_solver: pick_ik/PickIkPlugin
        kinematics_solver_timeout: 0.5
        kinematics_solver_attempts: 10
        mode: global
        stop_optimization_on_valid_solution: false
        position_scale: 1.0
        rotation_scale: 0.5
        position_threshold: 0.001
        orientation_threshold: 0.01
        cost_threshold: 0.001
        minimal_displacement_weight: 0.0
        gd_step_size: 0.0001
